### ISSUE TITLE
EG.net: Current Jackpot

### ISSUE THREAD

**Issue by Kingstead** [leondealmeida/PyCore#10]
This would be an enhancement.

Basically, a bot (or MySQL query?) could do a ?jackpot command every 30 minutes, store that information to a file (.txt, csv, or whatever). This information could then be viewed on the website and forum.

I thought about having that information display in the top right corner. Sounds like a feasible idea.

**Comment by Rek-SSU** [comment]
Easily done. I can do this.

**Comment by Kingstead** [comment]
Daggum son! You guys needa take notes! Haha.

**Comment by Rek-SSU** [comment]
Need to get with Junky and get this query set up.

**Comment by TheJunky** [comment]
do this query to get current jackpot,  i think it updates every 30 mins
"select jackpot from flag_games where arena REGEXP '^-?[0-9]+$' limit 1"

**Comment by TheJunky** [comment]
select jackpot from flag_games where arena REGEXP '^-?[0-9]+$' order by id
limit 1

**Comment by Rek-SSU** [comment]
Added to the site. Had to add "desc" to your order by statement.  Seems to
be working! Thanks Junk!

**Comment by Rek-SSU** [comment]
This can be closed.

**Comment by leondealmeida** [comment]
Woohoo
